### PR TITLE
Some new strings fr slap + new run module

### PR DESCRIPTION
**Pull request by HikaruIchijyo**
old one changed to lmr=let me run. and new one too run

### CODE REVIEW

**Comment by HikaruIchijyo** [comment]
@Muttahir786 @AvinashReddy3108

**Comment by HitaloM** [comment]
@Muttahir786 LMAO

**Comment by AvinashReddy3108** [comment]
> @Muttahir786 @AvinashReddy3108

Nice !!

**Comment by shxnpie** [comment]
@AvinashReddy3108 *on the bum*
What are u 3y/o Christian kid?

**Comment by AvinashReddy3108** [comment]
> @AvinashReddy3108 _on the bum_
> What are u 3y/o Christian kid?

Let's see what fun strings you got !!

**Pull request merged**
