### PR TITLE
New Module: Aria

### PR DESCRIPTION
**Pull request by shxnpie**
Added Aria for torrenting and stuff!
Just add this buildpack in Heroku and then deploy again.

`https://elements.heroku.com/buildpacks/amivin/aria2-heroku`

Tested, working!

### CODE REVIEW

**Comment by HikaruIchijyo** [comment]
@shxnpie url still having issue

**Comment by shxnpie** [comment]
@shxnpie @AvinashReddy3108 don't accept til I fix

**Comment by a092devs** [comment]
@AvinashReddy3108 Plox fix it

**Comment by AvinashReddy3108** [comment]
> @AvinashReddy3108 Plox fix it

which part exactly (or the whole module ??)

**Comment by a092devs** [comment]
@AvinashReddy3108 . url part as of now

**Comment by AvinashReddy3108** [comment]
> @AvinashReddy3108 . url part as of now

what part in .url exactly ??

**Comment by AvinashReddy3108** [comment]
Closing this PR, coz all bugs fixed.
will add in next update.

**Pull request closed without merging**
